import { Product } from '../_models/product';

export var PRODUCTS: Product[] = [
  {  kode_barang : 'BjW1' ,
    kode_tipe : 'DRESSES' ,
    nama_barang : 'Abaya Dress' ,
    deskripsi_barang : 'Desain Elegan dan berbahan kain lembut cocok digunakan pada saat acara resmi ' ,
    harga_barang : 350000 ,
    tanggal_datang : new Date('2016-11-12T00:00:00') ,
    ukuran : 'M',
    image : '../../image/1.jpg'} ,

  {  kode_barang : 'BjW2' ,
      kode_tipe : 'DRESSES' ,
      nama_barang : 'Lubeena Long Dress' ,
      deskripsi_barang : 'Desain baju yang simple , cocok untuk digunakan sehari-hari ' ,
      harga_barang : 250000 ,
      tanggal_datang : new Date('2016-11-12T00:00:00') ,
      ukuran : 'L',
      image : '../../image/2.jpg'} ,

  {  kode_barang : 'BjW3' ,
      kode_tipe : 'DRESSES' ,
      nama_barang : 'Shura Dress Cream' ,
      deskripsi_barang : 'Desain baju yang simple, cocok untuk digunakan sehari-hari ketika bersantai ' ,
      harga_barang : 250000 ,
      tanggal_datang : new Date('2016-11-12T00:00:00') ,
      ukuran : 'L',
      image : '../../image/3.jpg'} ,

  {  kode_barang : 'BjW4' ,
      kode_tipe : 'DRESSES' ,
      nama_barang : 'Messette Pleated Drees Pink' ,
      deskripsi_barang : 'Baju dengan warna yang eye catching ini sangat cocok digunakan untuk acara resmi dan sehari-hari ' ,
      harga_barang : 250000 ,
      tanggal_datang : new Date('2016-11-12T00:00:00') ,
      ukuran : 'L',
      image : '../../image/4.jpg'} ,

  {  kode_barang : 'BjW5' ,
     kode_tipe : 'DRESSES' ,
     nama_barang : 'Stripe Dress' ,
     deskripsi_barang : ' Desain yang simple namun memberikan kesan mewah cocok digunakan untuk sehari-hari ' ,
     harga_barang : 250000 ,
     tanggal_datang : new Date('2016-11-12T00:00:00') ,
     ukuran : 'L',
     image : '../../image/5.jpg'} ,

  {   kode_barang : 'BjW6' ,
      kode_tipe : 'DRESSES' ,
      nama_barang : 'Namira Long Dress' ,
      deskripsi_barang : 'Long dress dengan desain simple cocok untuk kamu yang ingin bersantai ' ,
      harga_barang : 300000 ,
      tanggal_datang : new Date('2016-11-12T00:00:00') ,
      ukuran : 'L',
      image : '../../image/6.jpg'},

  {  kode_barang : 'BjK1' ,
     kode_tipe : 'TOPS' ,
     nama_barang : 'Livia Blue Top' ,
     deskripsi_barang : 'Desain yang pas untuk pergi ke kantor, kampus dan tempat tempat lainnya ' ,
     harga_barang : 275000 ,
     tanggal_datang : new Date('2016-11-12T00:00:00') ,
     ukuran : 'L',
     image : '../../image/13.jpg'},

  {  kode_barang : 'BjK2' ,
     kode_tipe : 'TOPS' ,
     nama_barang : 'Moana Sequin White' ,
     deskripsi_barang : ' Produk best seller, berbahan kain tipis tapi tidak terawang dan sangat nyaman dipakai ' ,
     harga_barang : 350000 ,
     tanggal_datang : new Date('2016-11-12T00:00:00') ,
     ukuran : 'L',
     image : '../../image/14.jpg'},

  {   kode_barang : 'BjK3' ,
      kode_tipe : 'TOPS' ,
      nama_barang : 'Lucci Pattern' ,
      deskripsi_barang : 'Cocok untuk dipakai ke berbagai acara formal maupun acara informal ' ,
      harga_barang : 325000 ,
      tanggal_datang : new Date('2016-11-12T00:00:00') ,
      ukuran : 'L',
      image : '../../image/15.jpg'},

   {  kode_barang : 'BjK4' ,
      kode_tipe : 'TOPS' ,
      nama_barang : 'Christmast Eve' ,
      deskripsi_barang : ' Desain yang pas untuk pergi ke kantor, kampus dan tempat tempat lainnya' ,
      harga_barang : 50000 ,
      tanggal_datang : new Date('2016-11-12T00:00:00') ,
      ukuran : 'L',
      image : '../../image/16.jpg'},


  {  kode_barang : 'Spt1' ,
     kode_tipe : 'SHOES' ,
     nama_barang : 'Lumicca Platform Sandals' ,
     deskripsi_barang : 'sepatu yang termasuk kedalam kategori sneakers ini akan membuat para wanita lebih pede dengan tinggi badannya dengan bantuan hells ' ,
     harga_barang : 170000 ,
     tanggal_datang : new Date('2016-11-12T00:00:00') ,
     ukuran : 'L',
     image : '../../image/7.jpg'},

  {  kode_barang : 'Spt2' ,
     kode_tipe : 'SHOES' ,
     nama_barang : 'Zuletta Platform' ,
     deskripsi_barang : ' sangat nyaman untuk dipakai sehari-hari ' ,
     harga_barang : 165000 ,
     tanggal_datang : new Date('2016-11-12T00:00:00') ,
     ukuran : 'L',
     image : '../../image/8.jpg'},

  {  kode_barang : 'Spt3' ,
     kode_tipe : 'SHOES' ,
     nama_barang : 'Zevilla Cream Sandals' ,
     deskripsi_barang : 'sangat simple dan nyaman untuk dipakai sehari-hari ' ,
     harga_barang : 150000 ,
     tanggal_datang : new Date('2016-11-12T00:00:00') ,
     ukuran : 'L',
     image : '../../image/9.jpg'},

  {  kode_barang : 'Spt4' ,
     kode_tipe : 'SHOES' ,
     nama_barang : 'Ichibelle Sandals ' ,
     deskripsi_barang : 'Sangat cocok dan nyaman untuk dipakai sehari-hari ' ,
     harga_barang : 150000 ,
     tanggal_datang : new Date('2016-11-12T00:00:00') ,
     ukuran : 'L',
     image : '../../image/10.jpg'},

   {  kode_barang : 'Spt5' ,
      kode_tipe : 'SHOES' ,
      nama_barang : 'Jenewa Black Heels' ,
      deskripsi_barang : ' Desain simple namun memberikan kesan mewah, cocok untuk dipakai ke kantor maupun acara formal' ,
      harga_barang : 165000 ,
      tanggal_datang : new Date('2016-11-12T00:00:00') ,
      ukuran : 'L',
      image : '../../image/11.jpg'},

  {  kode_barang : 'Spt6' ,
     kode_tipe : 'SHOES' ,
     nama_barang : 'Assche Brown Sandals' ,
     deskripsi_barang : 'Sangat cocok dan nyaman untuk dipakai sehari-hari ' ,
     harga_barang : 112000 ,
     tanggal_datang : new Date('2016-11-12T00:00:00') ,
     ukuran : 'L',
     image : '../../image/12.jpg'},

  {  kode_barang : 'Acc1' ,
    kode_tipe : 'ACCESSORIES' ,
    nama_barang : 'Flowery Necklaces ' ,
    deskripsi_barang : ' Cocok dipakai pada saat acara formal ' ,
    harga_barang : 60000 ,
    tanggal_datang : new Date('2016-11-12T00:00:00') ,
    ukuran : 'L',
    image : '../../image/17.jpg'},

  {  kode_barang : 'Acc2' ,
      kode_tipe : 'ACCESSORIES' ,
     nama_barang : 'Storia Chain Glasses' ,
     deskripsi_barang : 'Gantungan kacamata yang super cute ' ,
    harga_barang : 75000 ,
     tanggal_datang : new Date('2016-11-12T00:00:00') ,
     ukuran : 'L',
     image : '../../image/18.jpg'},

  {  kode_barang : 'Acc3' ,
    kode_tipe : 'ACCESSORIES' ,
    nama_barang : 'Viumi Necklaces' ,
    deskripsi_barang : 'Kalung dengan desain yang simple ' ,
    harga_barang : 60000 ,
    tanggal_datang : new Date('2016-11-12T00:00:00') ,
    ukuran : 'L',
    image : '../../image/19.jpg'},

  {  kode_barang : 'Btm1' ,
    kode_tipe : 'BOTTOMS' ,
    nama_barang : ' Luppee Pleated Navy Pants' ,
    deskripsi_barang : 'Celana dengan desain yang simple dan nyaman dipakai ' ,
    harga_barang : 180000 ,
    tanggal_datang : new Date('2016-11-12T00:00:00') ,
    ukuran : 'L',
    image : '../../image/20.jpg'},


  {  kode_barang : 'Btm2' ,
    kode_tipe : 'BOTTOMS' ,
    nama_barang : 'Minato White Pleats Pants' ,
    deskripsi_barang : 'Celana dengan desain yang simple dan cute ' ,
    harga_barang : 190000 ,
    tanggal_datang : new Date('2016-11-12T00:00:00') ,
    ukuran : 'L',
    image : '../../image/21.jpg'},


  {  kode_barang : 'Btm3' ,
    kode_tipe : 'BOTTOMS' ,
    nama_barang : 'Minato Grey Pleats Pants' ,
    deskripsi_barang : 'Celana dengan desain yang simple ' ,
    harga_barang : 190000 ,
    tanggal_datang : new Date('2016-11-12T00:00:00') ,
    ukuran : 'L',
    image : '../../image/22.jpg'},
];
